included:
  - nasalis

excluded:
  - .build
  - .swiftpm
  - nasalis/Resources

disabled_rules:
  - cyclomatic_complexity
  - non_optional_string_data_conversion
  - redundant_string_enum_value
  - type_body_length
  - file_length
  - function_body_length
  - line_length
  - function_parameter_count
  - large_tuple
  - type_name

opt_in_rules:
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_optional_boolean
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicit_getter
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - lower_acl_than_parent
  - mark
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - function_name_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - implicit_optional_initialization
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
  - unneeded_break_in_switch
  - unused_control_flow_label
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_closing_braces
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition
  - reduce_boolean
  - nsobject_prefer_isequal
  - unowned_variable_capture
  - duplicate_enum_cases
  - legacy_multiple
  - closure_end_indentation
  - collection_alignment
  - comment_spacing
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - empty_xctest_method
  - file_header
  - identical_operands
  - identifier_name
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - nslocalizedstring_key
  - optional_enum_case_matching
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - reduce_into
  - self_in_property_initialization
  - static_operator
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - balanced_xctest_lifecycle
  - convenience_type
  - enum_case_associated_values_count
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - trailing_closure
  - unavailable_function
  - untyped_error_in_catch
  - xct_specific_matcher

attributes:
  always_on_same_line: ["@IBAction", "@IBSegueAction", "@NSManaged", "@escaping", "@objc", "@frozen"]

identifier_name:
  min_length: 1
  max_length:
    warning: 60
    error: 80
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error

inclusive_language:
  override_allowed_terms: ["master", "blacklist", "whitelist"]

nesting:
  type_level: 2
  function_level: 5

trailing_comma:
  mandatory_comma: true